### ISSUE TITLE
Support for HA Core?

### ISSUE THREAD

**Issue by ward0** [edwardtfn/HomeAssistant-Config#10]
The automation "auto update HA" (automation.auto_update_ha) has an action that calls an unknown service: hassio.host_reboot.

The same goes for backup, different command in Core version.

**Comment by edwardtfn** [comment]
I think this is quite easy to solve. The best solution would be replacing the on/off selector for boot to a dropdown where you select if booting the host or just HA or nothing, but that will be a breaking change. We can also do it in a uglier way having two inputs and don’t break existing installations.

**Comment by edwardtfn** [comment]
> The best solution would be replacing the on/off selector for boot to a dropdown where you select if booting the host or just HA or nothing

Done!
